#ifndef _ERROR_H
#define _ERROR_H

#define CommonACK_SUCCESS                                  0x0000 
#define CommonACK_KEY_ERROR                                0xFF00 
#define CommonACK_NO_AUTHORIZATION_ERROR                   0xFF01 
#define CommonACK_NO_RIGHTS_ERROR                          0xFF02 
#define CommonACK_NO_RESPONSE_ERROR                        0xFFFF 
#define CommonACK_MOTOR_FAIL_NONE                          0 
#define CommonACK_MOTOR_FAIL_COMPASS_ABNORMAL              1 
#define CommonACK_MOTOR_FAIL_ASSISTANT_PROTECTED           2 
#define CommonACK_MOTOR_FAIL_DEVICE_LOCKED                 3 
#define CommonACK_MOTOR_FAIL_IMU_NEED_ADV_CALIBRATION      5 
#define CommonACK_MOTOR_FAIL_IMU_SN_ERROR                  6 
#define CommonACK_MOTOR_FAIL_IMU_PREHEATING                7 
#define CommonACK_MOTOR_FAIL_COMPASS_CALIBRATING           8 
#define CommonACK_MOTOR_FAIL_IMU_NO_ATTITUDE               9 
#define CommonACK_MOTOR_FAIL_NO_GPS_IN_NOVICE_MODE         10 
#define CommonACK_MOTOR_FAIL_BATTERY_CELL_ERROR            11 
#define CommonACK_MOTOR_FAIL_BATTERY_COMMUNICATION_ERROR   12 
#define CommonACK_MOTOR_FAIL_BATTERY_VOLTAGE_TOO_LOW       13 
#define CommonACK_MOTOR_FAIL_BATTERY_USER_LOW_LAND         14 
#define CommonACK_MOTOR_FAIL_BATTERY_MAIN_VOL_LOW          15 
#define CommonACK_MOTOR_FAIL_BATTERY_TEMP_VOL_LOW          16 
#define CommonACK_MOTOR_FAIL_BATTERY_SMART_LOW_LAND        17 
#define CommonACK_MOTOR_FAIL_BATTERY_NOT_READY             18 
#define CommonACK_MOTOR_FAIL_RUNNING_SIMULATOR             19 
#define CommonACK_MOTOR_FAIL_PACK_MODE                     20 
#define CommonACK_MOTOR_FAIL_IMU_ATTI_LIMIT                21 
#define CommonACK_MOTOR_FAIL_NOT_ACTIVATED                 22 
#define CommonACK_MOTOR_FAIL_IN_FLYLIMIT_AREA              23 
#define CommonACK_MOTOR_FAIL_IMU_BIAS_LIMIT                24 
#define CommonACK_MOTOR_FAIL_ESC_ERROR                     25 
#define CommonACK_MOTOR_FAIL_IMU_INITING                   26 
#define CommonACK_MOTOR_FAIL_UPGRADING                     27 
#define CommonACK_MOTOR_FAIL_HAVE_RUN_SIM                  28 
#define CommonACK_MOTOR_FAIL_IMU_CALIBRATING               29 
#define CommonACK_MOTOR_FAIL_TAKEOFF_TILT_TOO_LARGE        30 
#define CommonACK_MOTOR_FAIL_RESERVED_31                   31 
#define CommonACK_MOTOR_FAIL_RESERVED_32                   32 
#define CommonACK_MOTOR_FAIL_RESERVED_33                   33 
#define CommonACK_MOTOR_FAIL_RESERVED_34                   34 
#define CommonACK_MOTOR_FAIL_RESERVED_35                   35 
#define CommonACK_MOTOR_FAIL_RESERVED_36                   36 
#define CommonACK_MOTOR_FAIL_RESERVED_37                   37 
#define CommonACK_MOTOR_FAIL_RESERVED_38                   38 
#define CommonACK_MOTOR_FAIL_RESERVED_39                   39 
#define CommonACK_MOTOR_FAIL_RESERVED_40                   40 
#define CommonACK_MOTOR_FAIL_INVALID_SN                    41 
#define CommonACK_MOTOR_FAIL_RESERVED_42                   42 
#define CommonACK_MOTOR_FAIL_RESERVED_43                   43 
#define CommonACK_MOTOR_FAIL_FLASH_OPERATING               44 
#define CommonACK_MOTOR_FAIL_GPS_DISCONNECT     45 
#define CommonACK_MOTOR_FAIL_INTERNAL_46        46 
#define CommonACK_MOTOR_FAIL_RECORDER_ERROR     47 
#define CommonACK_MOTOR_FAIL_INVALID_PRODUCT    48 
#define CommonACK_MOTOR_FAIL_RESERVED_49        49 
#define CommonACK_MOTOR_FAIL_RESERVED_50        50 
#define CommonACK_MOTOR_FAIL_RESERVED_51        51 
#define CommonACK_MOTOR_FAIL_RESERVED_52        52 
#define CommonACK_MOTOR_FAIL_RESERVED_53        53 
#define CommonACK_MOTOR_FAIL_RESERVED_54        54 
#define CommonACK_MOTOR_FAIL_RESERVED_55        55 
#define CommonACK_MOTOR_FAIL_RESERVED_56        56 
#define CommonACK_MOTOR_FAIL_RESERVED_57        57 
#define CommonACK_MOTOR_FAIL_RESERVED_58        58 
#define CommonACK_MOTOR_FAIL_RESERVED_59        59 
#define CommonACK_MOTOR_FAIL_RESERVED_60        60 
#define CommonACK_MOTOR_FAIL_IMU_DISCONNECTED   61 
#define CommonACK_MOTOR_FAIL_RC_CALIBRATING     62 
#define CommonACK_MOTOR_FAIL_RC_CALI_DATA_OUT_RANGE   63 
#define CommonACK_MOTOR_FAIL_RC_QUIT_CALI   64 
#define CommonACK_MOTOR_FAIL_RC_CENTER_OUT_RANGE   65 
#define CommonACK_MOTOR_FAIL_RC_MAP_ERROR   66 
#define CommonACK_MOTOR_FAIL_WRONG_AIRCRAFT_TYPE   67 
#define CommonACK_MOTOR_FAIL_SOME_MODULE_NOT_CONFIGURED   68 
#define CommonACK_MOTOR_FAIL_RESERVED_69   69 
#define CommonACK_MOTOR_FAIL_RESERVED_70   70 
#define CommonACK_MOTOR_FAIL_RESERVED_71   71 
#define CommonACK_MOTOR_FAIL_RESERVED_72   72 
#define CommonACK_MOTOR_FAIL_RESERVED_73   73 
#define CommonACK_MOTOR_FAIL_NS_ABNORMAL   74 
#define CommonACK_MOTOR_FAIL_TOPOLOGY_ABNORMAL   75 
#define CommonACK_MOTOR_FAIL_RC_NEED_CALI       76 
#define CommonACK_MOTOR_FAIL_INVALID_FLOAT      77 
#define CommonACK_MOTOR_FAIL_M600_BAT_TOO_FEW   78 
#define CommonACK_MOTOR_FAIL_M600_BAT_AUTH_ERR   79 
#define CommonACK_MOTOR_FAIL_M600_BAT_COMM_ERR   80 
#define CommonACK_MOTOR_FAIL_M600_BAT_DIF_VOLT_LARGE_1   81 
#define CommonACK_MOTOR_FAIL_BATTERY_BOLTAHGE_DIFF_82   82 
#define CommonACK_MOTOR_FAIL_INVALID_VERSION   83 
#define CommonACK_MOTOR_FAIL_GIMBAL_GYRO_ABNORMAL   84 
#define CommonACK_MOTOR_FAIL_GIMBAL_ESC_PITCH_NO_DATA   85 
#define CommonACK_MOTOR_FAIL_GIMBAL_ESC_ROLL_NO_DATA   86 
#define CommonACK_MOTOR_FAIL_GIMBAL_ESC_YAW_NO_DATA   87 
#define CommonACK_MOTOR_FAIL_GIMBAL_FIRM_IS_UPDATING   88 
#define CommonACK_MOTOR_FAIL_GIMBAL_OUT_OF_CONTROL   89 
#define CommonACK_MOTOR_FAIL_GIMBAL_PITCH_SHOCK   90 
#define CommonACK_MOTOR_FAIL_GIMBAL_ROLL_SHOCK   91 
#define CommonACK_MOTOR_FAIL_GIMBAL_YAW_SHOCK   92 
#define CommonACK_MOTOR_FAIL_IMU_CALI_SUCCESS   93 
#define CommonACK_MOTOR_FAIL_TAKEOFF_EXCEPTION   94 
#define CommonACK_MOTOR_FAIL_ESC_STALL_NEAR_GOUND   95 
#define CommonACK_MOTOR_FAIL_ESC_UNBALANCE_ON_GRD   96 
#define CommonACK_MOTOR_FAIL_ESC_PART_EMPTY_ON_GRD   97 
#define CommonACK_MOTOR_FAIL_ENGINE_START_FAILED   98 
#define CommonACK_MOTOR_FAIL_AUTO_TAKEOFF_LAUNCH_FAILED   99 
#define CommonACK_MOTOR_FAIL_ROLL_OVER_ON_GRD   100 
#define CommonACK_MOTOR_FAIL_BAT_VERSION_ERR   101 
#define CommonACK_MOTOR_FAIL_RTK_INITING       102 
#define CommonACK_MOTOR_FAIL_RTK_FAIL_TO_INIT   103 
#define CommonACK_MOTOR_FAIL_RESERVED_104   104 
#define CommonACK_MOTOR_FAIL_RESERVED_105   105 
#define CommonACK_MOTOR_FAIL_RESERVED_106   106 
#define CommonACK_MOTOR_FAIL_RESERVED_107   107 
#define CommonACK_MOTOR_FAIL_RESERVED_108   108 
#define CommonACK_MOTOR_FAIL_RESERVED_109   109 
#define CommonACK_START_MOTOR_FAIL_MOTOR_STARTED   110 
#define CommonACK_MOTOR_FAIL_INTERNAL_111      111 
#define CommonACK_MOTOR_FAIL_ESC_CALIBRATING   112 
#define CommonACK_MOTOR_FAIL_GPS_SIGNATURE_INVALID   113 
#define CommonACK_MOTOR_FAIL_GIMBAL_CALIBRATING   114 
#define CommonACK_MOTOR_FAIL_FORCE_DISABLE   115 
#define CommonACK_TAKEOFF_HEIGHT_EXCEPTION   116 
#define CommonACK_MOTOR_FAIL_ESC_NEED_UPGRADE   117 
#define CommonACK_MOTOR_FAIL_GYRO_DATA_NOT_MATCH   118 
#define CommonACK_MOTOR_FAIL_APP_NOT_ALLOW   119 
#define CommonACK_MOTOR_FAIL_COMPASS_IMU_MISALIGN   120 
#define CommonACK_MOTOR_FAIL_FLASH_UNLOCK    121 
#define CommonACK_MOTOR_FAIL_ESC_SCREAMING   122 
#define CommonACK_MOTOR_FAIL_ESC_TEMP_HIGH   123 
#define CommonACK_MOTOR_FAIL_BAT_ERR         124 
#define CommonACK_IMPACT_IS_DETECTED         125 
#define CommonACK_MOTOR_FAIL_MODE_FAILURE    126 
#define CommonACK_MOTOR_FAIL_CRAFT_FAIL_LATELY   127 
#define CommonACK_KILL_SWITCH_ON             135 
#define CommonACK_MOTOR_FAIL_MOTOR_CODE_ERROR   255 
#define ActivationACK_SUCCESS            0x0000 
#define ActivationACK_PARAMETER_ERROR    0x0001 
#define ActivationACK_ENCODE_ERROR       0x0002 
#define ActivationACK_NEW_DEVICE_ERROR   0x0003 
#define ActivationACK_DJIGO_APP_NOT_CONNECTED   0x0004 
#define ActivationACK_NETWORK_ERROR   0x0005 
#define ActivationACK_SERVER_ACCESS_REFUSED   0x0006 
#define ActivationACK_ACCESS_LEVEL_ERROR   0x0007 
#define ActivationACK_OSDK_VERSION_ERROR   0x0008 
#define ControlACK_SetControl_RC_MODE_ERROR   0x0000 
#define ControlACK_SetControl_RELEASE_CONTROL_SUCCESS   0x0001 
#define ControlACK_SetControl_OBTAIN_CONTROL_SUCCESS   0x0002 
#define ControlACK_SetControl_OBTAIN_CONTROL_IN_PROGRESS   0x0003 
#define ControlACK_SetControl_RELEASE_CONTROL_IN_PROGRESS   0x0004 
#define ControlACK_SetControl_RC_NEED_MODE_F   0x0006 
#define ControlACK_SetControl_RC_NEED_MODE_P   0x0005 
#define ControlACK_SetControl_IOC_OBTAIN_CONTROL_ERROR   0x00C9 
#define ControlACK_Task_SUCCESS        0x0000 
#define ControlACK_Task_MOTOR_ON       0x0001 
#define ControlACK_Task_MOTOR_OFF      0x0002 
#define ControlACK_Task_IN_AIR         0x0003 
#define ControlACK_Task_NOT_IN_AIR     0x0004 
#define ControlACK_Task_NO_HOMEPOINT   0x0005 
#define ControlACK_Task_BAD_GPS        0x0006 
#define ControlACK_Task_IN_SIMULATOR_MODE   0x0007 
#define ControlACK_Task_ALREADY_RUNNING   0x0008 
#define ControlACK_Task_NOT_RUNNING       0x0009 
#define ControlACK_Task_INVAILD_COMMAND   0x0010 
#define ControlACK_Task_NO_LANDING_GEAR   0x0011 
#define ControlACK_Task_GIMBAL_MOUNTED    0x0012 
#define ControlACK_Task_BAD_SENSOR        0x0013 
#define ControlACK_Task_ALREADY_PACKED    0x0014 
#define ControlACK_Task_NO_PACKED         0x0015 
#define ControlACK_LegacyTask_SUCCESS    0x0002 
#define ControlACK_LegacyTask_FAIL       0x0001 
#define ControlACK_Task_PACKED_MODE_NOT_SUPPORTED   0x0016 
#define ControlACK_SetArm_AIRCRAFT_IN_AIR_ERROR         0x0003 
#define ControlACK_SetArm_ALREADY_ARMED_ERROR 	       0x0002 
#define ControlACK_SetArm_OBTAIN_CONTROL_NEEDED_ERROR   0x0001 
#define ControlACK_SetArm_SUCCESS 		       0x0000 
#define ControlACK_KillSwitch_SUCCESS 		   0x00 
#define SubscribeACK_SUCCESS                  0x00 
#define SubscribeACK_ILLEGAL_DATA_LENGTH      0x01 
#define SubscribeACK_VERSION_DOES_NOT_MATCH   0x02 
#define SubscribeACK_PACKAGE_OUT_OF_RANGE     0x03 
#define SubscribeACK_PACKAGE_ALREADY_EXISTS   0x04 
#define SubscribeACK_PACKAGE_DOES_NOT_EXIST   0x05 
#define SubscribeACK_ILLEGAL_FREQUENCY        0x06 
#define SubscribeACK_PACKAGE_TOO_LARGE        0x07 
#define SubscribeACK_PIPELINE_OVERFLOW        0x08 
#define SubscribeACK_INTERNAL_ERROR_0X09      0x09 
#define SubscribeACK_PACKAGE_EMPTY            0x20 
#define SubscribeACK_INCORRECT_NUM_OF_TOPICS   0x21 
#define SubscribeACK_ILLEGAL_UID            0x22 
#define SubscribeACK_PERMISSION_DENY        0x23 
#define SubscribeACK_MULTIPLE_SUBSCRIBE     0x24 
#define SubscribeACK_SOURCE_DEVICE_OFFLINE   0x25 
#define SubscribeACK_PAUSED                 0x48 
#define SubscribeACK_RESUMED                0x49 
#define SubscribeACK_INTERNAL_ERROR_0X4A    0x4A 
#define SubscribeACK_FAILED_AUTHENTICATION    0x50 
#define SubscribeACK_VERSION_VERSION_TOO_FAR   0x51 
#define SubscribeACK_VERSION_UNKNOWN_ERROR   0x59 
#define SubscribeACK_INTERNAL_ERROR_0XFF     0xFF 
#define MissionACK_Common_SUCCESS           0x00 
#define MissionACK_Common_WRONG_WAYPOINT_INDEX   0x01 
#define MissionACK_Common_RC_NOT_IN_MODE_F   0xD0 
#define MissionACK_Common_OBTAIN_CONTROL_REQUIRED   0xD1 
#define MissionACK_Common_CLOSE_IOC_REQUIRED   0xD2 
#define MissionACK_Common_NOT_INITIALIZED   0xD3 
#define MissionACK_Common_NOT_RUNNING       0xD4 
#define MissionACK_Common_IN_PROGRESS       0xD5 
#define MissionACK_Common_TASK_TIMEOUT      0xD6 
#define MissionACK_Common_OTHER_MISSION_RUNNING   0xD7 
#define MissionACK_Common_BAD_GPS       0xD8 
#define MissionACK_Common_RTK_NOT_READY       0xCD 
#define MissionACK_Common_LOW_BATTERY   0xD9 
#define MissionACK_Common_VEHICLE_DID_NOT_TAKE_OFF   0xDA 
#define MissionACK_Common_INVALID_PARAMETER   0xDB 
#define MissionACK_Common_CONDITIONS_NOT_SATISFIED   0xDC 
#define MissionACK_Common_CROSSING_NO_FLY_ZONE   0xDD 
#define MissionACK_Common_UNRECORDED_HOME   0xDE 
#define MissionACK_Common_AT_NO_FLY_ZONE    0xDF 
#define MissionACK_Common_TOO_HIGH          0xC0 
#define MissionACK_Common_TOO_LOW           0xC1 
#define MissionACK_Common_TOO_FAR_FROM_HOME   0xC7 
#define MissionACK_Common_NOT_SUPPORTED   0xC8 
#define MissionACK_Common_TOO_FAR_FROM_CURRENT_POSITION   0xC9 
#define MissionACK_Common_BEGGINER_MODE_NOT_SUPPORTED   0xCA 
#define MissionACK_Common_TAKE_OFF_IN_PROGRESS   0xF0 
#define MissionACK_Common_LANDING_IN_PROGRESS   0xF1 
#define MissionACK_Common_RRETURN_HOME_IN_PROGRESS   0xF2 
#define MissionACK_Common_START_MOTORS_IN_PROGRESS   0xF3 
#define MissionACK_Common_INVALID_COMMAND   0xF4 
#define MissionACK_Common_UNKNOWN_ERROR     0xFF 
#define MissionACK_Follow_TOO_FAR_FROM_YOUR_POSITION_LACK_OF_RADIO_CONNECTION   0xB0 
#define MissionACK_Follow_CUTOFF_TIME_OVERFLOW   0xB1 
#define MissionACK_Follow_GIMBAL_PITCH_ANGLE_OVERFLOW   0xB2 
#define MissionACK_HotPoint_INVALID_RADIUS   0xC2 
#define MissionACK_HotPoint_YAW_RATE_OVERFLOW   0xC3 
#define MissionACK_HotPoint_INVALID_START_POINT   0xC4 
#define MissionACK_HotPoint_INVALID_YAW_MODE   0xC5 
#define MissionACK_HotPoint_TOO_FAR_FROM_HOTPOINT   0xC6 
#define MissionACK_HotPoint_INVALID_PAREMETER   0xA2 
#define MissionACK_HotPoint_INVALID_LATITUDE_OR_LONGITUTE   0xA3 
#define MissionACK_HotPoint_INVALID_DIRECTION   0xA6 
#define MissionACK_HotPoint_IN_PAUSED_MODE   0xA9 
#define MissionACK_HotPoint_FAILED_TO_PAUSE   0xAA 
#define MissionACK_WayPoint_INVALID_DATA   0xE0 
#define MissionACK_WayPoint_INVALID_POINT_DATA   0xE1 
#define MissionACK_WayPoint_TRACE_TOO_LONG   0xE2  /*!< This is the distance from WP1 to WPn. Newer A3/N3 FW > 60km  all others > 30km >*/
#define MissionACK_WayPoint_TOTAL_DISTANCE_TOO_LONG          0xE3  /*!< This is the distance from WP1 to WPn, plus distance from homepoint to WP1 and the distance from WPn back to the homepoint. Newer A3/N3 FW > 100km  all others > 60km >*/
#define MissionACK_WayPoint_POINT_OVERFLOW   0xE4 
#define MissionACK_WayPoint_POINTS_TOO_CLOSE   0xE5 
#define MissionACK_WayPoint_POINTS_TOO_FAR   0xE6 
#define MissionACK_WayPoint_CHECK_FAILED     0xE7 
#define MissionACK_WayPoint_INVALID_ACTION   0xE8 
#define MissionACK_WayPoint_POINT_DATA_NOT_ENOUGH   0xE9 
#define MissionACK_WayPoint_DATA_NOT_ENOUGH   0xEA 
#define MissionACK_WayPoint_POINTS_NOT_ENOUGH   0xEB 
#define MissionACK_WayPoint_IN_PROGRESS   0xEC 
#define MissionACK_WayPoint_NOT_IN_PROGRESS   0xED 
#define MissionACK_WayPoint_INVALID_VELOCITY   0xEE 
#define MissionACK_IOC_TOO_CLOSE_TO_HOME    0xA0 
#define MissionACK_IOC_UNKNOWN_TYPE         0xA1 
#define MFIOACK_init_SUCCESS                0x00 
#define MFIOACK_init_UNKNOWN_ERROR          0x01 
#define MFIOACK_init_PORT_NUMBER_ERROR      0x02 
#define MFIOACK_init_PORT_MODE_ERROR        0x03 
#define MFIOACK_init_PORT_DATA_ERROR        0x04 
#define MFIOACK_set_SUCCESS                 0x00 
#define MFIOACK_set_CHANNEL_ERROR           0x01 
#define MFIOACK_set_PORT_NOT_MAPPED_ERROR   0x02 
#define MFIOACK_get_SUCCESS                 0x00 
// clang-format on


#endif
